name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Alexis-Dim
          outputs: dist/github-contribution-grid-snake.svg
       
      - name: Push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          file: dist/*
